created navbar for Renaissance
sanskaromar/renaissance-2k23 pull request #15
Opened 2023-02-10 07:10 UTC by samjain233

**Desktop View**(devices haing vw>1024)
![image](https://user-images.githubusercontent.com/94921996/218024194-8b30d3bc-b29d-493c-ae58-d68b09821650.png)

**Tablet View**(vw > 768)
![image](https://user-images.githubusercontent.com/94921996/218024245-b10e245e-5886-4f71-87b5-91201b1bf02e.png)

**Mobile View**(vw ~ 425 )
![image](https://user-images.githubusercontent.com/94921996/218024294-e16ca2f9-d0cc-444d-b51b-935b8c2318b4.png)
![image](https://user-images.githubusercontent.com/94921996/218024327-c5fcb903-bb3e-4805-a185-ebee633c3164.png)

I have worked upon navbar section which is majorly [client/src/components/Navbar/Navbar.jsx] file , it requires a logo which is added in the Navbar folder .

**New Dependency** 

- Framer motion  (https://www.npmjs.com/package/framer-motion)

I also added two custom colours in the [client/tailwind.config.js] file

2023-02-11 07:16 UTC, PriyavKaneria requested changes
- For widths 768px to 1024px the "Confirm your seat button" disappears which should not be the case
![image](https://user-images.githubusercontent.com/43821039/218245890-f878ee0f-dd9a-4306-a30f-3cf58dc7713f.png)

- Either make the navbar take full height in mobile view or reduce the font sizes. Right now it looks too overwhelming

2023-02-11 18:11 UTC, sanskaromar commented on client/package.json
> +    "framer-motion": "^9.0.2",
Could have been done without framer-motion but this is also acceptable 👍

2023-02-11 19:15 UTC, NeerajChatterjee requested changes
As mentioned earlier, change the font size and make the confirm seat button visible from 768px to 1024px.
Also, if possible, try without the framer-motion library. It will increase the load on website later on.

2023-02-12 14:16 UTC, NeerajChatterjee approved these changes

2023-02-13 06:37 UTC, sanskaromar approved these changes

2023-02-13 06:37 UTC, merged