Team page
sanskaromar/renaissance-2k23 pull request #16
Opened 2023-02-10 15:59 UTC by Sambhav-Sam

![ecell](https://user-images.githubusercontent.com/97016770/218137344-93dd83d4-a316-4286-b713-b8a828b3cedf.png)

2023-02-11 13:11 UTC, sanskaromar requested changes

2023-02-11 13:11 UTC, sanskaromar commented on client/package.json
> +    "react-icons": "^4.7.1",
You icons from here for consistency in code as your other Team Mates are preferring this as well.

2023-02-11 13:11 UTC, sanskaromar commented on client/package.json
> +    "@mui/material": "^5.11.8",
We don't need MUI in our project as we are already using tailwind, and I don't thing MUI is required here.

2023-02-11 13:11 UTC, sanskaromar commented on client/public/index.html
> +    <script src="https://cdn.tailwindcss.com"></script>
We don't need tailwind cdn. Tailwind is installed in our project.

2023-02-11 13:11 UTC, sanskaromar commented on client/public/index.html
> +    </style>
index.html is not the best place to add CSS.
Try to use tailwind classes whenever possible.

2023-02-11 13:11 UTC, sanskaromar commented on client/public/index.html
>      <title>React App</title>
You edited everything but one thing that was actually necessary. The title.

2023-02-11 13:11 UTC, sanskaromar commented on client/src/components/TeamPage/CardTest.js
> +import TwitterIcon from "@mui/icons-material/Twitter";
Use react-icons

2023-02-11 19:08 UTC, NeerajChatterjee requested changes
As mentioned by Sanskar, remove the styling from index.html and use react-icons. Update the needful.

2023-02-11 19:34 UTC, vishwa511 requested changes
Make the icons more attractive on hover,  you can use scale property, since exact design is not provided use your own creativity
also the circle of same size covering the icon is not looking good, you can make it a bit bigger and can transform on hover
![snape](https://user-images.githubusercontent.com/76877878/218277598-211ffc06-1fad-4366-91be-5e0d92df0988.png)

2023-02-12 21:51 UTC, NeerajChatterjee submitted a review, later dismissed

2023-02-13 06:22 UTC, sanskaromar requested changes

2023-02-13 06:22 UTC, sanskaromar commented on client/public/index.html
> +    <title>Design Team</title>
This page is not for the design team. It's for Renaissance 2k23-Team.

2023-02-13 06:22 UTC, sanskaromar commented on client/src/components/TeamPage/CardTest.css
> +body {
Most of the things in this file could have been easily done with Tailwind.

2023-02-13 06:22 UTC, sanskaromar commented on client/src/components/TeamPage/CardTest.js
> +        </div>
Have you heard about components? Wouldn't it be easier to make this a separate component, and we pass their details via props whenever we want to add a new person?

2023-02-13 07:11 UTC, sanskaromar approved these changes

2023-02-13 07:11 UTC, merged