login/registration page implemented
sanskaromar/renaissance-2k23 pull request #17
Opened 2023-02-10 17:26 UTC by Wallbreaker100

DESKTOP VIEW (login page)

![Screenshot (65)](https://user-images.githubusercontent.com/97219962/218155676-0226d1e9-676e-49f2-b00b-22abdf426fec.png)

MOBILE VIEW(LOGIN PAGE)
![Screenshot (67)](https://user-images.githubusercontent.com/97219962/218155856-cb5cfd1c-cc98-4eec-aeb0-0dd4a1394934.png)

DESKTOP VIEW (REGISTRATION PAGE)
![Screenshot (68)](https://user-images.githubusercontent.com/97219962/218155973-0237230f-05ce-4d77-918f-369213984bd6.png)

MOBILE VIEW (LOGIN PAGE)
![Screenshot (71)](https://user-images.githubusercontent.com/97219962/218156064-2e543555-ba80-4a81-974f-ea8b539c8895.png)

I have implemented both the login and registration page . I have used 2 custom colors and a custom animation which is updated in tailwind.config.js file

2023-02-11 18:33 UTC, NeerajChatterjee requested changes
Add a check in the phone number field as well, i.e., the phone number can't be of just one digit. It should be of 10 digits.

![image](https://user-images.githubusercontent.com/73419394/218275106-cf87ede5-a478-46fa-86ee-8a3095fbb77e.png)
Also, in the above mobile view, it doesn't look good as the bottom of the container is completely empty. Fix the design issues and try to make it a bit more attractive.

2023-02-11 18:38 UTC, PriyavKaneria requested changes
![image](https://user-images.githubusercontent.com/43821039/218275219-b46570b3-83d1-452d-8595-098483556dad.png)
- In mobile view also center all content like you already did in signup
- Signup and login should feel seamless and not like different designs
- The Sign-in with social media does not contrast well with the bg so add proper size white bg circles for each (with proper padding and all)
- Gender has no validation. Gender with value gender is accepted which should not be the case

2023-02-12 07:58 UTC, NeerajChatterjee approved these changes

2023-02-12 08:50 UTC, sanskaromar requested changes

2023-02-12 08:50 UTC, sanskaromar commented on client/src/components/AuthPage/Background.jsx
> +          className="p-[5px] animate-linear_bubble flex items-center justify-center shadow-lg relative w-[24px] h-[24px] bg-bubble1 mr-[13px] ml-[13px] rounded-full"
mr-[13px] ml-[13px] can be mx-[13px] I guess. Is there any specific reason for writing like this? This is written like this in many lines.

2023-02-12 11:45 UTC, closed without merging